- hosts: localhost
  connection: local

  vars_files:
    - ansible_vars.yml

  tasks:
    - name: Get Disk ID
      ali_disk_info:
        alicloud_region: "{{ global.alicloud_region }}"
        name_prefix: "{{ disk.disk_name }}"
      register: disk_facts

    - name: Get Instance ID
      ali_instance_info:
        alicloud_region: "{{ global.alicloud_region }}"
        name_prefix: "{{ instance.instance_name }}"
      register: instances_facts

    - name: Attach disk to instance
      ali_disk:
        alicloud_region: "{{ global.alicloud_region }}"
        disk_id: "{{ item }}"
        instance_id: "{{ instances_facts.instances[0].id }}"
        delete_with_instance: "{{ disk.delete_with_instance }}"
      with_items: "{{ disk_facts.disk_ids }}"
