- hosts: localhost
  connection: local

  vars_files:
    - ansible_vars.yml

  tasks:
    - name: Get Disk ID
      ali_disk_info:
        alicloud_region: "{{ global.alicloud_region }}"
        name_prefix: "{{ disk.disk_name }}"
      register: disk_facts

    - name: Delete disk
      ali_disk:
        alicloud_region: "{{ global.alicloud_region }}"
        disk_id: "{{ item }}"
        state: absent
      with_items: "{{ disk_facts.disk_ids }}"
