---
- name: Performance tuning
  hosts: all
  tasks:
    - name: Enable irqbalance service
      service:
        name: irqbalance
        state: started

    - name: Get IOMMU status
      shell: dmesg | grep "IOMMU disabled"
      register: command_result
      ignore_errors: yes
      changed_when: no

    - block:
        - name: Disable IOMMU
          command: grubby --update-kernel=ALL --args="intel_iommu=off"
        - name: Restart managed host
          reboot:
            reboot_timeout: 120
            msg: "Ansible rebooting system for disabling IOMMU."
      when: "'IOMMU disabled' not in command_result.stdout"

    - name: Verify IOMMU disabled
      shell: dmesg | grep "IOMMU disabled"
      changed_when: no

    # - name: Enable NIC multiple queue
    #   script: ./scripts/config_nic_queues.sh optimized
